---
title: "Block 6 Overview"
pagetitle: "Block 6 Overview"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Block 6: Wrapping Up a Project

**Setup Pre-requisites:**

  * <a href="Block7_EXT-DMP-setup.html">Setup an account with the DMP Assistant</a> 
  * <a href="Block7_EXT-osfSetup.html">Setup an account with OSF</a>
  * <a href="Block7_EXT-Borealis.html">Setup an account with Borealis</a>



Today is all about depositing data and other materials for preservation and reuse after a research project is complete. We'll start with a presentation on data deposit and sharing as general concepts, considering what materials from a research project should be shared, and where they can be shared.  We will then discuss the concept of data repositories, with a specific focus on Borealis, a Canadian research data repository of which UVic has a dedicated instance.  We will then shift gears and jump back into our project files, finalizing the DMP we have been working on throughout the series, deciding what files from the series we'd like to deposit, and then finalizing the necessary documentation to accompany the deposited files.  Finally, we will do a hands-on data deposit using the demo instance of Borealis.

Below you'll find the overarching learning objectives for Block 6, as well as an overview of each session.

### Block 6 Learning Objectives

By the end of this block, you will be able to:

* Describe data sharing considerations when a research project is complete
* Articulate what should/shouldn't be shared after a research project is complete
* Define data repositories and their role in the research data lifecycle
* Discuss qualities of good data repositories
* Identify Borealis as a good data repository supported by UVic
* Identify FRDR as a good data repostiry for large datasets
* Complete a DMP for a research project
* Complete a README and necessary documentation for a data deposit
* Deposit a dataset and accompanying materials into Borealis

### Block 6 Session Overviews

#### Session 1: Data Deposit and Sharing

* Why would you share data?
* What to share vs. what to keep
* Additional considers when sharing data
* Reasons you might not share data
* Data repositories
  * General description
  * Borealis
  * FRDR
* Data licenses

#### Session 2: DMP and Project Wrap-Up

* Review the current DMP for the series and make any necessary updates to complete the document (as best we can!)
* Review the files that we have created in the series and decide which should be deposited
* Update the README document for the series to reflect the files we will deposit

#### Session 3: Borealis Deposit

* Hands-on data deposit using the Borealis demo instance







