---
title: "R Cheatsheet"
pagetitle: "R Cheatsheet"
output:
  html_document:
    code_folding: show # allows toggling of showing and hiding code. Remove if not using code.
    code_download: true # allows the user to download the source .Rmd file. Remove if not using code.
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
    smooth_scroll: false
---
  
## R Cheatsheet
  
  Below are all the commands that are used in the RDM Jumpstart for quick access.  In addition to this cheatsheet, you can find more detailed documentation online (a quick search of a function will usually guide you in the right direction), but the following documentaion sites are valuable references as you continue to grow your R skills:
  
  - <a href="https://www.tidyverse.org/">Tidyverse documentation</a>
  - <a href="https://rstudio.github.io/renv/articles/renv.html">Introduction to renv</a>
  - <a href="https://yihui.org/tinytex/">TinyTex</a>

:::md-table
  
  | Command | Description | Syntax
| :--- | :----- | :---- |
| `<-` | Assign content to an R object. | `object-name <- content-assigned` |
| `read.csv()` | Read data into R. It's advised to assign to an R object). | ` data <- read.csv("file-path/data-file-name.csv")` |
| `write.csv()` | Save data used/created in R as a .csv file. | `write.csv(data, "file-path/file-name.csv")` |
| `colnames()` | List all the column names in a dataset. | `colnames(data)` |
| `head` | Display the top rows of a dataset. Can optionally include a specified number after a comma. | `head(data, 10)` |
| `View()` | Display a dataset as a spreadsheet within an RStudio window. | `View(data)` |
| `install.packages()` | Install a package into R. Only need to do this once. | `install.packages("package-name")` |
| `library()` | Bring a package to use by calling its library. | `library(package-name)` |
| `names()` | Display a list of all the column names in a data object. | `names(data)` |
| `|>` | The pipe operator, which takes the output of one command/function and passes it through to another, and can be thought of as "and then" in your code. | `data <- data |> function(...)` |
| `save()` | A way to save R objects in a specified file. | `save(data, file="file-path/file-name.file-extension")` |
| `load()` | Import saved R objects from a file. | `load(file-path/file-name.file-extension)` |
| `rename()` | Allows you to rename column names (variables) of a dataset. | `data <- data |> rename("new-column-name" = "old-column-name")` |
| `mean()` | Calculates the mean of the data that's placed in the brackets. | `mean(data)` | 
| `sum()` | Returns the sum of all the values present in the argument. | `sum(function(data$variable)` |
| `is.na()` | Display when a variable or dataframe has missing values, presented as TRUE/FALSE. | `is.na(data$variable)` |
| `complete.cases()` | Display when a row has no missing values, presented as TRUE/FALSE | `complete.cases(data)` |
| `class()` | Returns the class of an object to indicate the data structure. | `class(data)` |
| `recode()` | Change data format of variables or re-categorize certain values in a variable as some other value.  Often used in conjunction with `mutate` (see below for example). |
| `mutate()` | Create new columns based on values in existing columns. | `data <- data |> mutate(new-variable-name = recode(data$old-variable, "old-value" = "new-value"))` |
| `class()` | Prints the data type of a variable, or the structure of a dataset. | `class(object-of-interest)` |
| `is.numeric` | Check to see if the data is of a numeric class, which will return a TRUE/FALSE response. `is.numeric(data)` |
| `as.numeric()` | Converts alternative data types into numeric values. | `as.numeric(data)` |
| `distinct()` | Display distinct values of a variable. | `data %>% distinct(variable)` |
| `count()` | Counts the number of occurrences of each value in a column. | `data |> count(variable)` |
| `arrange()` | Display outcome results in ascending or descending order (default is ascending) | `data %>% arrange(desc(value-of-interest))` |
| `filter` | Subset the data to keep only rows where a specified condition is met. | `data |> filter(variable-value == x)` |
| `nrow()` | Returns the number of rows present in x. | `nrow(data)` |
| `ncol()` | Returns the number of columns present in x. | `ncol(data)` |
| `print(paste())` | Print output with a string variable together. | `print(paste("print this string with possible R objects"))` |
| `select()` | Select specific columns from a dataset, usually used in part of a pipe.  To select multiple columns, separate with commas. |`r-object |> select(variable1, variable2)` |
| `summarise` | Creates a new dataframe, and will saummarise all observations from the input. |`summarise(R-object)` |
| `ggplot()` | A library to make plots from your data.  The usage of ggplot ranges from very simple to very detailed, so for further information on usage see the Day 4 section on Visualizations, or read the documentation above on the Tidyverse. |
| `gzfile() ` | Used to compress/zip files in R to create a smaller file that's easier to store and share. | `gzfile("file-path/file-name.file-extension)` |
`ggsave` | Save a ggplot graphic as a .png or .pdf file. There are many arguments that can fit into this, and you can read more in the tidyverse documentation at the top of the page| `ggsave("file-path/file-name.file-extension", arguments)` |
`tiff` | Save a graphic as a .tiff file. Like `ggsave`, there are many arguments that can fit into `tiff`, and you can read more about in the documentation | `tiff("file-path/file-name.tiff", arguments)` |

:::
