---
title: "Roadmap to RDM"
pagetitle: "Roadmap to RDM"
output:
  html_document:
    code_folding: show # allows toggling of showing and hiding code. Remove if not using code.
    code_download: true # allows the user to download the source .Rmd file. Remove if not using code.
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## A Roadmap to RDM

:::md-table
| Concept | Reason |
| :--- | :--- |
| Make a plan. | Research without a plan is ripe for bias and headaches. |
| Update your plan as you go. | Things change, keep track of these changes. |
| Conduct a risk assessment of your data. | Understand and communicate the the impacts of release of your data. |
| Document the file types, data types, and applications you intend to use. | Prepare for, and select, the 'best' options for your project. |
| Select an appropriate storage location for you data. | This should align with any and or all of: a) your risk assessment; b) participant consent forms; c) ethics review; d) data sharing agreements; e) data licences; f) funder requirements. |
| Keep backups. | Don't lose all of your hard work. |
| Maintain robust documentation and metadata. | Document tacit knowledge. |
| Establish a retention schedule. | Don't keep things for longer than you need. |
| Deposit your data. | Ensure transparency and adhere to insitutional, funder, and / or publisher requirements. |
:::


