---
title: "Installing R and RStudio"
pagetitle: "Installing R and RStudio"
output:
  html_document:
    code_folding: show # allows toggling of showing and hiding code. Remove if not using code.
    code_download: true # allows the user to download the source .Rmd file. Remove if not using code.
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## R and RStudio Setup

We will be using R and RStudio to handle data manipulation and exploration, and the first step is going to be getting these tools setup on your computer. It can be a bit confusing at first (we’ll cover this more in the Jumpstart courses!), but R is the coding language that we’ll be using, and RStudio is a piece of software that makes running R much more friendly. In order for everything to work correctly, you will need to download both separately:

## Downloading R and RStudio

Link to download R and RStudio (download R first, then RStudio): [https://posit.co/download/rstudio-desktop/](https://posit.co/download/rstudio-desktop/)

## Installation Instructions

For detailed instructions providing video walkthroughs of how to download R and RStudio for both Mac and Windows, you can connect to the follow page produced by the UVic Digital Scholarship Commons: [https://uviclibraries.github.io/rstudio/pre-workshop.html](https://uviclibraries.github.io/rstudio/pre-workshop.html)
