---
title: "Block 3 Overview"
pagetitle: "Block 3 Overview"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Block 3: Moving into Coding and Computational Reproducibility

**Setup Pre-requisites:**

  * <a href="Block7_EXT-DMP-setup.html">Setup an account with the DMP Assistant</a>
  * <a href="Block7_EXT-osfSetup.html">Setup an account with OSF</a>
  * <a href="Block7_EXT-RRStudio.html">Download R and RStudio</a>
  
### Welcome to Block 3 of the UVic RDM Jumpstart!

In this block we're going to start dipping our toes in the world of coding with the R coding language.  We'll begin by discussing the pros and cons of using Excel for working with spreadsheet data, and how moving into a coding language like R, and working with plain-text files like `.csv` files, is much more conducive to open and transparent research. We will then do a very interactive introduction to R and RStudio, including an introduction to the environment, basic syntax and foundational concepts, and will create our first reproducible R script.

Below you'll find the overarching learning objectives for Block 3, as well as an overview of each session.

### Block 3 Learning Objectives

By the end of this block, you will be able to:

* Identify issues with reproducibility in research, and best practices to make research reproducible
* Discuss pros and cons of using Excel for spreadsheet data
* Articulate the difference between Excel files (`.xlsx`) and plain-test `.csv` files, and their role in reproducibility
* Define scripting and the concept of literate programming
* Situate the data science workflow within the research data lifecycle
* Begin applying the syntax of an R script to conduct basic actions
* Create reproducible code by applying concepts of literate programming

### Block 3 Session Overviews

#### Session 1: Reproducible Research and Moving from Excel to Scripting

* What is reproducibility in research?
* The reproducibility crisis
* What can we (as librarians) do?
* Nuances of reproducibility and best practices
* Diving into Excel
  * What it does well
  * What it doesn't do so well
* `.xlxs` vs. `.csv` files
* Scripting and literate programming
* The data science workflow with R
* Update additional sections of the project DMP

#### Session 2: 

* Introduce R and RStudio
* Setting up in R
  * File types in R
  * Creating a project
  * Setting up a working directory
* Creating our first R script
* Saving files locally and backing up to OSF
* Updating additional sections of the project DMP



















