---
title: "Documentation in Action"
pagetitle: "Documentation in Action"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Documentation in Action

Now that we've gotten a sense of how documentation looks in the wild, we can now start completing a README for the project that we'll be working on throughout the program.  We'll begin by opening the `README-template.txt` document that was downloaded from OSF.  If you haven't yet done this, or are having issues finding it, please see the session **"Block 1 - Introduction to OSF"**, for instructions, or ask your program instructor.  


### Quick Link to README Template
Here is a quick link to the template for you to quickly download, if needed: [README template](https://ecommons.cornell.edu/items/7dc55694-0131-499b-8df1-fa676c2589e6)


A few things to note:

* You may notice that the document looks a bit jittery and isn't the friendliest thing to read.  This is because it is a **plain text document**, meaning that it has none of the formatting of a Microsoft Word document, but can be opened by any operating system.  It might take a little bit of getting used to, but using plain text is an important factor in making out work FAIR.

* It's also possible that you might not be able to complete every section of a README at the start of a project - and that's ok!  This **should** be a living document that is regularly updated, and it's good to think of how you might implement an update schedule, either by yourself or among your project collaborators.

* This will be the place that you can write down your naming convention and folder structure that you created.  If things change during a project, it's no problem!  This is where the updating schedule comes in handy, and we'll be returning to the README throughout the series to update it accordingly.

**Let's jump in and start filling it out!**


### Update the DMP


:::question

Once you have finished completing as much of the README as you can at this point, return to the <a href="https://dmp-pgd.ca/">DMP Assistant</a> and updated the following questions:

* **Section 1: Data Collection** 
    * Does the data you will be working with contain sensitive information that requires data protection considerations? For example: (Select all that apply)
    
* **Section 2: Documentation and Metadata**
    * What documentation will be created for the data to be read and interpreted correctly in the future?
    * How will you make sure that documentation is created or captured consistently throughout your project?
    * Do you plan to use a metadata standard and/or tools to document and describe your data? If so, please list here.
    
* **Section 7: Sensitive Data and Legal Compliance**
    
:::
    
    
    
    




















