---
title: "DMP and Project Wrap-Up"
pagetitle: "DMP and Project Wrap-Up"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## DMP and Project Wrap-Up

This session is going to be a bit of a free-form exercise in wrapping a project up.  For those that haven't been following along for the whole program, you can access the project files that we'll be discussing here: <a href="https://osf.io/rx5a3/">UVic RDM Jumpstart OSF</a>

There are 3 main goals we're going to work through, and will follow them in sequential order:

1) Review the current DMP and make any necessary updates to complete the document as best we can;
2) Review the files that we have and decide which should be deposited, and which should be kept (but not deposited) or discarded;
3) After deciding which files we will deposit, update the README document to reflect any changes which will prepare us for the data deposit in the next session.

<br>

### DMP Wrap-Up

So far we have addressed the following questions in the DMP:

* **Section 1: Data Documentation**
  * What types of research data will you collect, create, link to, acquire and/or record?
  * What file formats will your data be collected and saved in? Select all that apply.
  * Does the data you will be working with contain sensitive information that requires data protection considerations? For example: (Select all that apply)
  * Describe how you will organize, name, and version-control your files to help you and others understand your data.
  * Describe related tools and software needed to access, manipulate, and analyze the data.

* **Section 2: Documentation and Metadata**
  * What documentation will be created for the data to be read and interpreted correctly in the future?
  * How will you make sure that documentation is created or captured consistently throughout your project?
  * Do you plan to use a metadata standard and/or tools to document and describe your data? If so, please list here.

* **Section 3: Storage and Backup**
  * What are the anticipated storage requirements for your data, in terms of storage space (in megabytes, gigabytes, terabytes, etc.) and the length of time you will be storing it?
  * How and where will your data be stored and backed up during your research project?
  * If applicable, where are hardcopy notebooks and physical samples going to be physically stored?
  * How will the research team and other collaborators access, modify, and contribute data throughout the project?

* **Section 4: Preservation**
  * Indicate how you will ensure your data is preservation friendly before archiving. Consider preservation-friendly file formats, anonymization and de-identification of human subjects data, long-term file integrity, and inclusion of supporting documentation.

<br>

:::question

The task now is to jump back into the <a href="https://dmp-pgd.ca/">DMP Assistant</a> and see if we can complete the sections we haven't yet completed, which consist of the following 3 sections:

* Section 4: Preservation
* Section 5: Sharing and Reuse
* Section 8: Responsibilities and Resources

It might also be valuable to review the questions you have already answered, and see if they need any updating or if you're happy with how you originally filled them in.

:::

<br>

### What Should We Keep?

If you've been following along with the whole program, you can go to your OSF fork or your local storage to take a look at the files you have.  If you're just jumping in now, you can go to the <a href="https://osf.io/rx5a3/">UVic RDM Jumpstart OSF</a> to get a sense of the files that were generated.

:::question

1) What files do you think need to be deposited?
2) Are there any files you think should be kept locally, but not deposited?
3) Are there any files you think can be discarded?

:::

<br>

### Finalizing Documentation

Now that we've established the files that we want to deposit, we want to make sure the accompanying documentation is sufficient for others to be able to interpret and reuse our work.

Let's first take a look at the <a href="https://libguides.uvic.ca/researchdata/dataverse/depositguidelines">UVic Borealis Deposit Guidelines</a>

:::question

1) Is there anything in the README document that is unclear or needs to be udpated?
2) Noting that we created a few extra variables, this is where we would update the data dictionary.  However, for the purpose of this session we won't do that due to a bit of technical knowledge needed to do so, but let's discuss what would be needed to update.
3) Is there anything else that we might need to do before we're ready to deposit?

:::


## Save Your Work

Let's wrap things up by saving our files locally and exporting the DMP from the DMP Assistant, deleting any unneeded files, and backing everything up to OSF.















