---
title: "Naming Conventions and Folder Structure"
pagetitle: "Naming Conventions and Folder Structure"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Naming Conventions and Folder Structure for the Project

Now that we've learned some of the principles of RDM and file and folder organization, let's put these theories to work!

First, let's open up the OSF repository for the UVic RDM Jumpstart.  If you haven't yet done this, see the session on **"Introduction to OSF"**, or talk to your instructor.

Now, let's start by looking at the README file that is embedded in the repository wiki, which describes all the files that we have, as well as how the files are organized in OSF storage.

<object class = "pdf" data = "images/Block2-2_OSF-readme.pdf"></object>

<br>

### Activity

Looking at the file list, and how the files are organized, you might think that it's a bit messy - which it is!  While we all want to avoid a mess in our work, it's very common for things to become a bit unweildy throughout the course of a project.  The goal of this activities is to use the theories that were discussed in the session on **"Organizing Files and Folders"**, and to apply this knowledge to cleaning up these files.

Let's try to approach this challenge in the following way:

1) First, look through the files try to determine what they are, and classify them based on their role/type/function:
    * Are they data files?
    * Are they coding scripts?
    * Are they administrative documents?
    * Something else?
    
2) After you feel that you've got a decent grasp on the files we have, the next step is to develop a folder hierarchy (if you think it needs one) to help organize the files.  There is no **"right"** way to do this, as long as you follow the principles that were discussed in the previous session and follow best practices in naming.  The goal of this is to think about how you will interact and access the files, and what might be the easiest way to facilitate this.


3) The next step is to determine what kind of naming convention you want to use.  Again, there is no **"right"** way to do this, as long as you follow the principles of file naming discussed in the previous session.  Think about the idea of applying conceptual elements to a naming convention, and what elements you think would be best to organize this file list.  Document your naming convention, but don't rename the files just yet!

4) Now that you have a folder hierarchy and file naming convention, here comes the fun part...  Let's delete all the files in the OSF repo **except for the following files**:
<br>
    * GSS29_PUMF_main_v3.pdf
    * license.txt
    * README-template.txt
    * timeuse_block-4_first-steps.csv
    * timeuse_block-5_visualization.csv
    * timeuse_block-5_visualization.RData
    * timeuse_data-dictionary.md
    * timeuse_data-dictionary.pdf
    
    
If you've done this successfully, you will have these remaining 8 files in your repo.  If you did make a mistake, you can easily retrieve the files from the original repo, or talk to your instructor.

This might seem like a brash move to delete all these files, but in a real research project, you don't get the ability to see all the files you will generate at the onset.  This exercise was meant to give you a sense of what can be generated in a project and how to think about setting up your work, but now that you've done so, let's ground ourselves in reality and start back at square 1!

5) In OSF, rename the remaining files according to the naming convention by clicking on the three dots on the far right side next to the file, and selecting *"Rename"*.

6) Add the folders you developed (if one was developed), by clicking the green arrow button at the top right side of the screen, and selecting *"Create folder"*

7) Next, move any files into associated folders, by clicking the three dots on the right right side next to the file, and selecting *"Move"*, then choosing the appropriate folder.

6) Finally, download this folder to your personal machine.  This will take a couple steps:

  * Click *"Download this folder"* at the top right of the screen.  
  * This will create a `.zip` archive in your `Downloads` folder.  
    * On a Mac, you can click on the archive, and it will create a new folder in your `Downloads` folder.
    * On a Windows machine, you can right-click the archive and select *"Extract All"*, and select where you want the files to go.
    
**For the purposes of this series, save this folder in your `Documents` folder, which should be attached to your OneDrive**.  If you have any issues with this process, please ask your instructor.


Finally, **Keep your naming convention handy**, as we'll return to it in a little while, but first let's move onto the next session to learn a bit about documentation.








