---
title: "Documentation"
pagetitle: "Documentation"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Documentation

* [Download the PowerPoint](files/Block2-3_Documentation.pptx)

<object class = "pdf" data = "files/Block2-3_Documentation.pdf"></object>


### Activity

**Take a look at the following datasets:**

* Kampen, Andrea; Pearson, Maggie; Smit, Michael, 2018, "Replication Data for: Digital Tools and Techniques in Scholarship and Pedagogy in the Social Sciences and Humanities", [https://doi.org/10.23685/1H9TOV](https://doi.org/10.23685/1H9TOV)

* Livingstone, D.W., 2021, "7 Replication Data for: 2017 CWKE Registered Nursing Dataset", [https://doi.org/10.5683/SP2/I98O1W](https://doi.org/10.5683/SP2/I98O1W)

* Perron, Maxime, 2023, "Interindividual variability in the benefits of personal sound amplification products on speech perception in noise: a randomized cross-over clinical trial", [https://doi.org/10.5683/SP3/HTMDLI](https://doi.org/10.5683/SP3/HTMDLI)

<br>

**Questions**

* What kind of documentation do you see?
* Can you tell what each of the files is?
* When looking at a data file, can you understand what you're looking at?
* Is there anything that sticks out to you as interesting?  Good?  Bad?


### Dataset for the program

[https://doi.org/10.5683/SP3/RDS0CK](https://doi.org/10.5683/SP3/RDS0CK)



