---
title: "Block 1 Overview"
pagetitle: "Block 1 Overview"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Block 1: Basics of Research Data Management (RDM)

**Setup Pre-requisites:**

  * <a href="Block7_EXT-DMP-setup.html">Setup an account with the DMP Assistant</a>
  * <a href="Block7_EXT-osfSetup.html">Setup an account with OSF</a>


### Welcome to Block 1 of the UVic RDM Jumpstart!

In this Block we're going to kick things off with a high-level introduction of the most fundamental aspects of Research Data Management (RDM).  We'll then move into an introduction to data management plans (DMPs), by providing an overview of the questions and considerations of a DMP, and then doing an introduction to the DMP Assistant, which is a Canadian tool to help produce DMPs, and we'll create a new DMP.  We will then move to an introduction to the Open Science Framework (OSF), which is an online storage platform that supports good RDM practices and facilitates collaboration, and through this platform will discuss and demonstrate concepts of data backup and version control, and spend some time investigating the project files that we will be working with throughout the Jumpstart program.  We'll wrap this block up by returning to the DMP Assistant and begin answering a couple questions.  Throughout the program we'll be returning to the DMP Assistant, and filling in questions as new concepts are introduced.

Below you'll find the overarching learning objectives for Block 1, as well as an overview of each session.

### Block 1 Learning Objectives

By the end of this block, you will be able to:

* Define what research data are and what research data management (RDM) is.
* Articulate the importance of RDM in the context of research outputs.
* Discuss the data services offered by the UVic Libraries.
* Identify data management plans (DMPs) as a way to realize good RDM practices.
* Begin summarizing the questions and considerations of a DMP.
* Navigate the DMP Assistant.
* Situate the Open Science Framework (OSF) within the research data lifecycle.
* Describe concepts of version control as it relates to research data and associated tools.

### Block 1 Session Overviews


#### Session 1: Introduction to Research Data Management (RDM)

* What are research data?
* What is RDM?
* The research data lifecycle
* Why is RDM important?
  * Academic integrity
  * Tri-Agency RDM Policy
  * FAIR and CARE Principles
* UVic Libraries' Data Services

<br>

#### Session 2: Introduction to Data Management Plans (DMPs)

* What is a DMP?
* High-level overview of the questions and considerations of a DMP
* Introduction to the DMP Assistant and hands-on walk-through
* Creating a DMP

<br>

#### Session 3: Introduction to the Open Science Framework (OSF)

* What is OSF?
* Why would you use it?
* Introduction to version control, and how OSF's automated version control will be used throughout the program.
* Getting started with OSF and hands-on walk-through.
* Getting acquainted with the project files that will be used throughout the program.
* Begin filling in DMP for the program project.








