---
title: "Roadmap to Reproducibility"
pagetitle: "Roadmap to Reproducibility"
output:
  html_document:
    code_folding: show # allows toggling of showing and hiding code. Remove if not using code.
    code_download: true # allows the user to download the source .Rmd file. Remove if not using code.
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## A Roadmap to (Computational) Reproducibility

Once data are collected...

:::md-table
| Concept | Reason |
| :--- | :--- |
| Do not use a GUI, use a script. | A script can be rerun. |
| Use an IDE that supports projects, ensuring that references are relative to the root working directory. | The script can be ported to another machine. |
| Do not overwrite variables, generate a new, derived variable. | Allows you to trace errors. |
| Use version control. | Track changes over time for workflow transparency. |
| Maintain Documentation. | Keep a record of tacit knowledge. |
| Use a language and approach that supports literate programming.<sup>1</sup> | Make your code intelligible to others. |
| Manage your code to: a) separate exploratory and confirmatory analyses (use notebooks, like RMarkdown); b) maximize reuse (use scripts for frequently reused code); and c) limit accidentally overwriting objects (functional programming). | Maintain clear delineations between instructions and outputs (functional programming), minimize mistakes / errors (code reuse), separate hypothesis generation from hypothesis testing (notebookes). |
| Use open file formats and when possible ones that have formal standards. | Maximize persistence in time and portability across software and hardware. |
| Document your: a) Operating System and version; b) Program and version; c) External packages and version. | Provide a replicable computational framework. |
| Find a way to account for dependencies - these may be language specific, operating specific, hardware specific.<sup>2</sup> | Provide a "package" that is a replicable framework. |
:::

<br />
<hr />
<br />

<sup>1</sup>  
"Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do."

<sup>2</sup>  
How to Account for Dependencies:

* renv() for language specific
* containers for OS
* emulators for hardware


