---
title: "Block 2 Overview"
pagetitle: "Block 2 Overview"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Block 2 Overview

**Setup Pre-requisites:**

  * <a href="Block7_EXT-DMP-setup.html">Setup an account with the DMP Assistant</a>
  * <a href="Block7_EXT-osfsetup.html">Setup an account with OSF</a>
  

### Welcome to Block 2 of the UVic RDM Jumpstart!

In this block we're going to start diving into the finer details of RDM, starting with an outline of best practices in file naming and folder organization.  We're then going to jump back in to the OSF repo for the program, and take a closer look at the files for the project, and collaboratively develop a file naming convention and folder hierarchy.  We will then shift to a discussion of various forms of data documentation, with a specific focus on README documents.  This will be followed by a some concepts and considerations in data licensing, and then we will wrap things up by beginning to fill out a README document for the program project, as well as updating more sections of the project DMP.

Below you'll find the overarching learning objectives for Block 2, as well as an overview of each session.

### Block 2 Learning Objectives

By the end of this block, you will be able to:

* Describe best practices in file naming, including elements that contribute to human and machine readability.
* Develop a file naming convention and folder hierarchy for a research project.
* Create a README document for a research project.
* Further your ability to complete a DMP.


### Block 2 Session Overviews

#### Session 1: Organizing Files and Folders

* Introduce concepts and best practices in file naming
  * Human readability
  * Machine readability
* Best practices in directory (folder) structures
* Versioning files via file naming

#### Session 2: Naming Conventions and Folder Structure for the Project

* Revisit the files in the project and collaboratively develop a naming convention
* Collaboratively develop an appropriate directory structure for the project
* Update the project DMP

#### Session 3: Documentation

* Identify the importance of documentation as it relates to RDM and the FAIR Principles
* Key concepts to cover in a README document
* Data dictionaries as an alternative/additional form of documentation
* Discuss general best practices of data licensing, and how it pertains to the project's data

#### Session 4: Documentation in Action

* Begin filling out a README for the project using a README template
* Update additional DMP sections












