---
title: "Code of Conduct"
pagetitle: "Code of Conduct"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Code of Conduct

RDM Jumpstart seeks to provide a welcoming, engaging, fun, and safe experience for everyone. By attending the program, participants agree to support and help cultivate an experience that is collaborative, respectful, and inclusive. We do not tolerate harassment in any form. Discriminatory language and imagery, including sexual or sexualized language and imagery, is not appropriate for any Zoom session, Slack channel, email, or other channel.

Harassment is understood as any behavior that threatens or demeans another person or group, or that produces an unsafe environment. It includes, but is not limited to, offensive verbal comments or non-verbal expressions related to gender, gender identity, gender expression, sexual orientation, disability, physical appearance, body size, race, ethnicity, age, religious or political beliefs; sexual, sexualized, or discriminatory images in public (including online) spaces; deliberate intimidation, stalking, or following; harassing photography or recording; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention.

We reserve the right to remove participants who harass other participants or members of the RDM Jumpstart team.

This code of conduct has been adapted from the Code4Lib code of conduct, available at [https://github.com/code4lib/code-of-conduct/blob/main/code_of_conduct.md](https://github.com/code4lib/code-of-conduct/blob/main/code_of_conduct.md), and the We Keep Each Other Safe(r) guidelines from the Community Research Data Toolkits Workshop, available at [https://community-data-toolkits-workshop.github.io/CDTW/conduct/](https://community-data-toolkits-workshop.github.io/CDTW/conduct/).  