---
title: "Contributors"
pagetitle: "Contributors"
output:
  html_document:
    includes:
      after_body: footer.html
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Contributors

In alphabetic order…

Erin McCoy, Gia-Huy Hoang, Jane Fry, Jennifer Abel, Maria Amoros-Teijeiro, Mathew Vis-Dunbar, Nick Rochlin

<hr />

**Erin McCoy**  
Research Assistant, Carleton University

Erin McCoy is a PhD Candidate in Social Psychology at Carleton University. Her research focuses on friendship and gossip behavior. 

**Gia-Huy Hoang**  
Research Assistant, University of Calgary

Gia-Huy Hoang is a second-year Master’s student in Neuroscience from University of Calgary. His research is on machine learning models using psychosocial and neuroimaging data to predict the first onset of anxiety and depression in high-risk adolescents, using data from the large Adolescent Brain Cognitive Development (ABCD) study.

**Jane Fry**  
Data Services Librarian, Carleton University

Jane Fry is the Data Services Librarian at MacOdrum Library, Carleton University. She has been 'doing data' for over 25 years. This includes helping researchers at all levels to discover, understand, and use data. Research data management is her other main area of responsibility, and she collaborates regularly with the data community by participating in various RDM initiatives, both in leadership roles and as a member. She has also participated in several provincial, national, and international committees in various positions, from Chair to member, including the ICPSR Governing Council, the Portage and Alliance Training Expert Groups, the Ontario data community, and Carleton's Institutional RDM Strategies Working Group. Some of her other activities include being a national Data Champion and a peer reviewer for various data publications.

**Jennifer Abel**  
Research Data Management Librarian, University of Calgary

Jennifer Abel is the Research Data Management Librarian at the University of Calgary, having joined the library in May 2023 from the Research Services Office. Prior to coming back to UCalgary in December 2021, after many years away, she was the Training Coordinator for the Portage Network, an RDM-focused initiative of the Canadian Association of Research Libraries, and for the RDM team in the Digital Research Alliance of Canada. Jennifer is the co-chair of the National Training Expert Group for the Canadian RDM Network of Experts. She holds a PhD in Linguistics and an MLIS from the University of British Columbia, and has taught at UCalgary, UBC and Mount Royal.

**Maria Amoros-Teijeiro**  
Research Assistant, University of Victoria

Maria Amoros-Teijeiro is a PhD candidate in Educational Psychology at the University of Victoria. Originally from the Dominican Republic, she holds a bachelor’s degree in Psychology from INTEC (Dominican Republic) and a master’s in Educational Research from the Universidad de Valladolid (Spain). From 2017 to 2022, she taught research methods at INTEC, coordinated a program aimed at introducing young scholars to educational research, and worked as a researcher at the Dominican Institute of Research, Evaluation and Quality in Education (IDEICE). Passionate about data and research, she moved to Victoria, BC in 2022 to begin her doctoral studies.

**Mathew Vis-Dunbar**  
Data Librarian, University of British Columbia, Okangan

Mathew Vis-Dunbar is the Data Librarian at the University of British Columbia's Okanagan (UBCO) campus. In addition to supporting researcher needs related to data, he works with faculty and students to promote open and transparent research practices.

**Nick Rochlin**  
Data Science Librarian, University of Victoria

Nick Rochlin is the Data Science Librarian at the University of Victoria (UVic).  Prior to joining UVic, he was the Research Data Management (RDM) Specialist with the University of British Columbia’s Advanced Research Computing team, where he provided assistance and instruction to researchers in accessing and using digital research infrastructure, as well as all things RDM.  In his current role, he focuses on supporting researchers in RDM and reproducible research workflows, and bridging the gap between UVic’s Library and Research Computing Services.  He has participated in a number of national roles in Canada’s data ecosystem, and is currently the Co-chair of the Digital Research Alliance of Canada’s RDM National Training Expert Group.

